### ISSUE TITLE
Support for yarn v1 lock

### ISSUE THREAD

**Issue by fersilva16** [smarlhens/npm-pin-dependencies#81]
Hey! I'm trying to run this on a yarn monorepo and it seems like this package only works with the NPM lock file.

Do you have plans on supporting the yarn v1 lock file?

**Comment by smarlhens** [comment]
Hey 👋🏻 

Thanks for reaching out ! 

I will add it for the next release. I don't know yet when I'll have time to do it but it can be done quickly I think.

Reference: 
- https://classic.yarnpkg.com/lang/en/docs/yarn-lock/
- https://github.com/yarnpkg/yarn/tree/master/packages/lockfile
